import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('index.html', 'dist/index.html');
await cp('data', 'dist/data', { recursive: true });
await mkdir('dist/server', { recursive: true });
await mkdir('dist/.openai', { recursive: true });
await cp('.openai/hosting.json', 'dist/.openai/hosting.json');
await writeFile('dist/server/index.js', `export default { async fetch(request) { const url = new URL(request.url); const path = url.pathname === '/' ? '/index.html' : url.pathname; return fetch(new URL(path, request.url)); } };\n`);
console.log('Static site ready in dist');
